name: profiler
description: Switch between Kid, Focus and Work profiles that block apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  crypto: ^3.0.5
  profiler_blocker:
    path: packages/profiler_blocker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
